# Generated by Django 2.2.18 on 2021-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('img', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=225)),
                ('price', models.IntegerField()),
                ('sale', models.BooleanField(default=True)),
            ],
        ),
    ]
