# Generated by Django 2.2.18 on 2021-07-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20210716_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
    ]
