# Generated by Django 2.2.18 on 2021-07-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210708_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='even_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='email',
            new_name='web',
        ),
    ]
