# Generated by Django 2.2.18 on 2021-07-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210713_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upated',
            new_name='updated',
        ),
    ]
