# Generated by Django 2.2.18 on 2021-07-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210713_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='image',
        ),
    ]
